### PR TITLE
#1 Fix Incorrect Maven Project Structure

### PR DESCRIPTION
**Pull request by Sxtanna**
This PR addresses the issue raised in #1

- Updates the project structure to properly follow maven's convention
- Updates the maven pom to include details about the requirements for building
  - Java 20
  - Preview Enabled
- Updates the maven pom to declare that it should build in UTF-8 mode
- Updates the gitignore to properly ignore the maven build directory `target/`
- Merges contents of extra readme into the main readme

### CODE REVIEW

**Comment by byronka** [comment]
This is not a Maven project.

**Comment by Sxtanna** [comment]
> This is not a Maven project.

Even if it's not a "maven project" per se. It should still follow these basic universally standard conventions.

The project requires significant extra work to begin development on, and forcing this non standardized approach only makes working with it harder for yourself and everyone else..

**Comment by byronka** [comment]
> only makes working with it harder for yourself

After many years of working with tools like Maven and Gradle, I wanted to experiment with some approaches outside my ken.  So far, the speed and flow I've experienced have been better than what Maven offered.  Common convention does not neccessarily make something the best approach.  I wanted to irreverently explore what better could look like.  This is the result.  It may end up badly, but that is a chance I am taking.

The /java directory that Maven requires is superfluous - it does little for me.  Consistency for the sake of consistency does me no service, regardless of the prevalence of that opinion.

When working with Make, I have the entirety of Unix at my disposal.  I am able to achieve nearly everything I want with one or two well-chosen commands.  In Maven, I have to find or build a plugin, because anything else is anti-convention.  

Developers are currently too concerned, in my opinion, with convention and consistency.  I think it is because of the complexity and confusion of what we do.  But we don't need to dismiss our ability - if we build properly - that is, with good documentation and testing, and building slowly, and reflecting on what we have built - we can build good systems that last.

I do not expect to persuade you.  I have generally found that is impossible to do.  But I can tell you how I am thinking, and you are welcome to your opinion.

**Comment by Sxtanna** [comment]
> The /java directory that Maven requires is superfluous - it does little for me.

The reasoning here is kinda wonky, conventions don't exist to directly serve you and only you. The java directory within src/main exists as the central point for java source files.
If you _(impersonal you)_ wanted to add Kotlin code to this project, you would put that into the Kotlin directory, etc etc... 

For 99% of projects that pure java, it does little. But that doesn't mean it does nothing, and further is doesn't mean it hurts...

> Consistency for the sake of consistency does me no service, regardless of the prevalence of that opinion.

I honestly can't even begin to understand this... If your goal is to be a contrarian, why stop at project structure? Name your classes using completely random styles, break every other convention while you're at it...

It seems more like you just dislike maven/gradle and you're arguing against consistency to justify that, rather than just saying you don't like them...

> When working with Make, I have the entirety of Unix at my disposal. I am able to achieve nearly everything I want with one or two well-chosen commands. In Maven, I have to find or build a plugin, because anything else is anti-convention.

Except you lose platform agnosticism, project agnosticism, and general reproducibility without major modification...

Not to mention you're STILL using maven... ?
All of the work done with make so that you don't have to use maven, and you're still using it? I don't understand...

Your development guideline has paragraphs after paragraphs explaining useless details maven would already handle for you, and then your quick start guide literally uses maven in the example project..?

If its so bad to be consistent and simple, why not create your own publishing system, host your jar in your own repository system, and have your guide reference how to handle all of that?

**Comment by Sxtanna** [comment]
> Developers are currently too concerned, in my opinion, with convention and consistency. I think it is because of the complexity and confusion of what we do. But we don't need to dismiss our ability - if we build properly - that is, with good documentation and testing, and building slowly, and reflecting on what we have built - we can build good systems that last.

> I do not expect to persuade you. I have generally found that is impossible to do. But I can tell you how I am thinking, and you are welcome to your opinion.


I also don't expect to persuade at this point considering the nonsense, but at least just say you don't like maven. The feigned philosophical high road is very boring and gross.

**Comment by byronka** [comment]
Flies with honey and all that.

**Pull request closed without merging**
